[package]
name = "deckocr"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.97"
dirs = "6.0.0"
eframe = "0.31.1"
egui_extras = "0.31.1"
global-hotkey = "0.6.4"
image = "0.25.6"
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.140"
xcap = "0.4.1"
